---

#
# Setup/install tasks.
#

- include: Debian.yml
  when: ansible_os_family == 'Debian'

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'
